name: release

on:
  workflow_call:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch
        required: true
        type: string
      subpackage_name:
        description: |
          Used in Git tag prefix.
        required: true
        type: string
      # XXX: does not skip for some reason
      # skip_tests:
      #   description: |
      #     Skip tests iff === 'true'
      #   required: true
      #   default: 'false'

env:
  # Disable git hooks
  HUSKY: 0

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['22.x']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Create a new version
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.next_version != 'skip' }}
        shell: bash
        run: |
          GIT_TAG_PREFIX=${{ inputs.subpackage_name }}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Running `pnpm version` to translate `minor` to semver string:
          new_version=$(pnpm version --no-git-tag-version --new-version ${{ github.event.inputs.next_version }})
          git add -u
          git commit -m "chore: Release ${GIT_TAG_PREFIX}/${new_version}"
          git pull --rebase
          git tag -a "${GIT_TAG_PREFIX}/${new_version}" -mBump
          # Push commit along with tag
          git push origin --tags :

      - name: Build all subpackages
        run: pnpm dist

      # https://github.com/pnpm/pnpm/issues/3141#issuecomment-1305563972
      - name: Configure npm/pnpm for publishing
        shell: bash
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PANERON_CI_NPM_TOKEN }}

      - name: Publish to npm
        working-directory: ./packages/${{ inputs.subpackage_name }}
        run: |
          pnpm publish dist --access public --no-git-checks
